from __future__ import annotations

from core.logger import Logger
from core.models import Session, Task, TaskStatus
from tools.filesystem import ensure_dir, write_file


class DeveloperAgent:
    def __init__(self, session: Session):
        self.session = session
        self.logger = Logger(session.id)

    def run_task(self, task: Task) -> Task:
        task.status = TaskStatus.RUNNING

        self.logger.info(
            event="task_started",
            detail=task.title,
        )

        project_dir = ensure_dir(self.session.brief.project_dir)

        if task.title == "Create README":
            path = project_dir / "README.md"

            content = f"""# {self.session.brief.title}

{self.session.brief.description}

Generated by NeuralOptima.
"""

            write_file(str(path), content)
            task.files_created.append(str(path))
            task.result_summary = "README.md generated."

        elif task.title == "Create requirements.txt":
            path = project_dir / "requirements.txt"

            content = """fastapi
uvicorn
"""

            write_file(str(path), content)
            task.files_created.append(str(path))
            task.result_summary = "requirements.txt generated."

        elif task.title == "Create app.py":
            path = project_dir / "app.py"

            content = '''from fastapi import FastAPI

app = FastAPI()


@app.get("/")
def root():
    return {"message": "NeuralOptima API running"}
'''

            write_file(str(path), content)
            task.files_created.append(str(path))
            task.result_summary = "app.py generated."

        else:
            task.result_summary = "Unknown task."

        task.status = TaskStatus.DONE

        self.logger.info(
            event="task_completed",
            detail=task.title,
        )

        return task
